# Generated by Django 6.0.5 on 2026-06-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsafar', '0002_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
