# Generated by Django 6.0.5 on 2026-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsafar', '0003_trip_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
